spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false

springdoc:
  api-docs:
    enabled: ${SWAGGER_API_DOCS_ENABLED:false}
  swagger-ui:
    enabled: ${SWAGGER_UI_ENABLED:false}

logging:
  level:
    root: INFO
    com.placement.platform: INFO
