export { default as Landing } from './Landing';
export { default as Login } from './Login';
export { default as Register } from './Register';
export { default as ForgotPassword } from './ForgotPassword';
export { default as VerifyEmail } from './VerifyEmail';
export { default as NotFound } from './NotFound';
export * from './Landing';
export * from './Login';
export * from './Register';
export * from './ForgotPassword';
export * from './VerifyEmail';
export * from './NotFound';
